name: Build and Package on Tag Push

on:
  push:
    tags:
      - "*"

jobs:
  build-and-package:
    name: Build and Package
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        arch:
          - x64
          - arm64
        node-version:
          - 16
        os:
          - linux
          - macos
          - windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Compile Typescript to Javascript for Packaging
        run: npm run build

      - name: Package into Node.js binary
        uses: lando/pkg-action@v2
        with:
          entrypoint: bin/cli
          arch: ${{ matrix.arch }}
          node-version: ${{ matrix.node-version }}
          os: ${{ matrix.os }}
